config/urls.py
from django.contrib import admin
from django.urls import path, include
#from myproject.api.live_transactions import second_node_socket
from myproject.api.views import home_page
urlpatterns = [
    path('', home_page, name='home_page'),
    path('admin/', admin.site.urls),
    path('', include('myproject.api.urls')),
]
# async def test():
#     await second_node_socket()

myproject/api/urls.py
from django.conf.urls import url

from .views import(
                    search_transaction,
                    get_neighbors_for_first_node,
                    get_neighbors_for_second_node,
                    home_page,
                    distribute_task,
                    create_seed,
                    create_address,
                    detail
                    

                  )

app_name='api'
urlpatterns = [
    url(r'search/$',search_transaction, name = 'search_transaction'),
    url(r'neighbor1/$',get_neighbors_for_first_node, name = 'neighboor1'),
    url(r'neighbor2/$',get_neighbors_for_second_node, name = 'neighboor2'),
    #url(r'',home_page, name = 'homepage'),
    url(r'distribute_task/$',distribute_task, name = 'distribute_task'),
    url(r'create_seed/$',create_seed, name = 'create_seed'),
    url(r'create_address/$',create_address, name = 'create_address'),
    url(r'^track/(?P<pk>[0-9a-f-]+)/$', detail,
        name = 'track'
       )

]

myproject/api/models.py
from django.db import models
from django.contrib.auth.models import User




class nodes(models.Model):
    name = models.CharField(max_length=200,
                            unique=True 
                              )
    type = models.CharField(max_length=200,
                            default = "IOTA node" 
                              )

    
    def __str__(self):
        return self.name

class inputs(models.Model):
    input = models.CharField(max_length=200,
                              )
    tt = models.CharField(max_length=200,
    blank = True, null= True,
                            unique=True
                              )
    # node = models.ForeignKey(nodes, on_delete=models.CASCADE,
    #                           blank = True, null= True
    #                          )
    #problem = models.ForeignKey(problem, on_delete=models.CASCADE
    #                         )               
    def __str__(self):
        return self.input

class outputs(models.Model):
    output = models.CharField(max_length=200,
    blank = True, null= True
          
                )
    problem = models.ForeignKey("problem", on_delete=models.CASCADE,
                              blank = True, null= True
                             ) 
    

    input = models.ForeignKey(inputs, on_delete=models.CASCADE
                            )               
    node = models.ForeignKey(nodes, on_delete=models.CASCADE,
                              blank = True, null= True
                             )
     

class problem(models.Model):
    problem_tag= models.CharField(max_length=200,
                                  blank = True, null= True
                              )
    
    # proccessor = models.ForeignKey(nodes, on_delete=models.CASCADE,
    #                           blank = True, null= True
    #                                    )
    
    input = models.ManyToManyField("inputs", through='outputs')
    final_answer = models.CharField(max_length=200,
                                   default="not computed"
                                  )
    # output =  models.CharField(max_length=200,
    #                            null = True, blank=True
    #                           )
    def __str__(self):
       return  self.final_answer

myproject/api/views.py
import time
import uuid
from zmq.sugar import context
from django.views.generic import ListView, CreateView, DetailView
from myproject.api.models import outputs, problem, nodes,inputs
from django.shortcuts import render, redirect
from django.http import HttpResponse 
from iota.crypto.types import Seed
from .form import InputForm
from iota import( Iota, 
                  ProposedTransaction, 
                  Address,
                  Tag,
                  TryteString,
                )

seed_for_first_node = "YIZXIJNLRSFU9OGCTBJJPGVRXDEZVVFELZQUK9K9VFWBQLULQZRBRCLIVCQVSIIIMZPQVDTRRLWDAWSRL"
seed_for_second_node = "NHBDVRADCXJJYCSOJAPTITGHVULNUZIKKUKRMTM9IWXBTY9BPHUMDKVCMWEJQYQEDJLADKATNCZKX9HYO"
seed_for_third_node = "OU9BABBPHGHXQFEIZOMCIFJAP9AFZSUJJJYTUZSK9BZBHWTURMRRPVPFQWAQRTNCKOHJRIEVZJQBPMHEN"
address_for_first_node = 'EA9IAPVJCLJTBJCFERWTPZRBBGZEXDXKIXVPEWLQJZSYJTUTLCJYVKNYJLDZZSZMMSYDJCRTITMVPBNHY'
address_for_second_node = "LBHMLPDSSLNVKORURUWQ9WZKSCKTUYBELBJIMZQEHWVWWXAPUAFQENFCTYGSRIIGKOSVMAOYCOIOLJGKC"
address_for_third_node = "FWOSYILPVJPYNUTBPCQLRLGKMXWDGBCNMGLGVWAUKGSHNODRFIRIUGTGFVYSALMBWXTMJBJWALICHFOWA"


def home_page(request):
    return render(request,
                 'api/home_page.html'
                  )


def search_transaction(request):
    seed = 'DQNEMZUAQTIQLAJ9NUXWPGBMRKAMWBHSAEZSOKPYOYBEFYJ9IEVKTYZY9XOI9WWNRJLJPSV9CQ9KBHMK9' 
    api_2 = Iota('http://localhost:14266',seed)
    #result = api.send_transfer(transfers = [fictional_transactions])
    result_hash = "W9PBQMJENXYDFGDZSKOPVOUCHOQQOHTZ9QLUPVUAREOUVPOMXTWOSVYPPUUYVEJMTMODLXZVIPERZ9999"
    bd_2 = api_2.get_bundles(result_hash)
    return HttpResponse(bd_2['bundles'][0].get_messages()) 

def get_neighbors_for_first_node(request):
    
    api = Iota('http://127.0.0.1:14267',)
    #print(api.get_node_info())
    #inf = api.get_node_info()
    return HttpResponse("hhhhhhhhhhhhh")

def get_neighbors_for_second_node(request):
    api = Iota('http://node1:14265')
    print(api.get_neighbors())
    neighbors = api.get_neighbors()
    return HttpResponse(neighbors["neighbors"])


def create_seed(request):
    my_seed = Seed.random()
    return HttpResponse(my_seed)


def create_address(request):
    api = Iota('http://localhost:14268',)
    address = api.get_new_addresses(index=0, count=1, security_level = 1)['addresses'][0]
    print(address)
    return HttpResponse(address)


def distribute_task(request):
    form = InputForm()
    tt = str(uuid.uuid4())
    ttt = tt[0:12]
    T=TryteString.from_unicode(ttt)
    print("tag is ......:",tt)
    tagg = Tag(T)
    if request.method == "POST":
        api = Iota('http://node1:14265',seed_for_first_node)
        form = InputForm(request.POST)
        if form.is_valid():
            
            in_1 = str(form.cleaned_data['input_1'])
            in_2 = str(form.cleaned_data['input_2'])
            inputlist = [in_1,in_2]
            message_2 = TryteString.from_unicode(in_1)
            message_3 = TryteString.from_unicode(in_2)
            fictional_transactions_2 = ProposedTransaction(
            address=Address(address_for_second_node),
            tag = tagg,
            message=message_2,
            value=0,
            )
            fictional_transactions_3 = ProposedTransaction(
            address=Address(address_for_third_node),
            tag = tagg,
            message=message_3,
            value=0,
            )
            problem.objects.create(problem_tag = str(tagg))
            result = api.send_transfer(transfers = [fictional_transactions_3,fictional_transactions_2],min_weight_magnitude=9)
            pp = nodes.objects.filter(type="IOTA node")
            print(pp)
            j = 0
            new_problem = problem.objects.get(problem_tag = str(tagg))
            print(new_problem)
            for i in pp:
                ttt = str(uuid.uuid4())
                inputs.objects.create(input= inputlist[j],tt=ttt)
                iii = inputs.objects.get(tt=ttt)
                outputs.objects.create(node = i,input = iii, problem = new_problem)
                j+=1
            return redirect('/track/{}'.format(new_problem.id))
    context = {
        "form" :form
    }
    return render(request,
                 'api/distribute_task.html',
                  context          
                  )

def detail(request,pk):
    problemm = problem.objects.get(id=pk)
    final = problemm.final_answer
    outs = outputs.objects.filter(problem = problemm)
    a = 0
    final_answerr = 0
    for out in outs:
        if out.output is None:
            a+= 1
        else:
            outt = out.output
            final_answerr+= int(outt)
    if a==0:
        final = final_answerr

    context = {
        "outs":outs,
        "final":final,

        }
 
    return render(request,'api/problem_detail.html',context)

myproject/templates/api/distribute_task.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}
{% block content %}

<div class="row">
    <div class="col-md-4">
        <div class="card">
          <div class="card-header">
            <h5 class="card-title">IOTA-Based Distributed Computing</h5>
          </div>
          <ul class="list-group list-group-flush">
            <a href="{% url 'api:distribute_task' %}"  class="list-group-item list-group-item-action">Distribute Problem</a>
            <a href="{% url 'api:distribute_task' %}" class="list-group-item list-group-item-action">Private Network Info</a>
            <a href="#" class="list-group-item list-group-item-action">Others</a>

          </ul>
        </div>
    </div>
<div class="col-md-5">
    <div class="card card-outline-secondary">
        <div class="card-header bg-warning">
            <h3 class="mb-2" style="margin-left:20%">Please insert inputs </h3>
        </div>
        <div class="card-body">
            <form   action=""class="form" method="POST" role="form" autocomplete="off" novalidate>
                {% csrf_token %}
                <div class="form-group" style = "margin-left:20%">
                    in_1: {{ form.input_1 }}
                    
                </div>
                </br>
                <div class="form-group" style = "margin-left:20%">
                    in_2: {{ form.input_2 }}
                </div>
                </br>
                <button  type="submit" class="btn btn-warning btn-sm" style="margin-left:45%">submit</button>
				
            </form>
                     
        </div>
	</div>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock %}

myproject/templates/api/home_page.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}
<!doctype html>

{% block content %}
<div class="row">
<div class="col-md-4">
<div class="card">
  <div class="card-header">
    <h5 class="card-title">IOTA-Based Distributed Computing</h5>
  </div>
  <ul class="list-group list-group-flush">
    <a href="{% url 'api:distribute_task' %}" style= "width 30%" class="list-group-item list-group-item-action">Distribute task</a>
    <a href="#" style= "width 30%" class="list-group-item list-group-item-action">Private network info</a>
    <a href="#" class="list-group-item list-group-item-action">Create new task</a>
    <a href="#" class="list-group-item list-group-item-action">All tasks</a>
    
  </ul>
</div>
</div>
  <div class="col-md-8">
  <p>Iotagrid is an IOTA-based distributed computing system that computes complex tasks by distributing 
  it in the IOTA network. First application(Demo) of the system is computing f(x,y) = x^2 + y^2. We will add more tasks in 
  the future. In this task, user insert its two inputs and then system distributes inputs among IOTA nodes. When nodes calculate their outputs, they send it to the 
  network. Finally, the first node calculates the final answer. Payment will be added to the system in the near future.
  </p>
  </div>

</div>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock %}

   

myproject/templates/api/problem_detail.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}
<!doctype html>

 
{% block content %}
<div class ="row">
<div class="col-4">
<div class="card">
          <div class="card-header">
            <h5 class="card-title">IOTA-Based Distributed Computing</h5>
          </div>
          <ul class="list-group list-group-flush">
            <a href="{% url 'api:distribute_task' %}"  class="list-group-item list-group-item-action">Distribute Problem</a>
            <a href="{% url 'api:distribute_task' %}" class="list-group-item list-group-item-action">Private Network Info</a>
            <a href="#" class="list-group-item list-group-item-action">Others</a>

          </ul>
        </div>
        </div>
  <div class ="col-6">
  <div class="card">
  {% comment %} <div class="container justify-content-center">
  <div class="row table-responsive"> {% endcomment %}
  <div  class = "card-header bg-warning">
  <h5 style ="margin-left:31%;" class="card-title">Answer detail</h5>
  </div>
  <div class= "card-body">
<table style ="width:100%;" class=" table table-responsiv table-bordered  justify-content table-hover table-striped">
                <thead class="thead-ligh thead-dark" >
                    <th>node</th>
                    <th>input </th>
                    <th>output </th>
                  </thead>
                <tbody class="table-hover" >
                    {% for out in outs %}
                            <tr>
                                <td >{{out.node}}</td>
                                <td>{{out.input}}</td>
                                {% if out.output  %}
                                 <td >{{out.output}}</td> 
                                {%else%}
                                <td>not computed yet</td>
                                {%endif%}
                            </tr>
                       
                    {% endfor %}
                    </tbody>
                </table>
                </div>
                <div class="card-footer bg-warning">
                <h5 style="margin-left:30%">The final answer is: <code> {{final}} </code></h5>
                </div>
</div>
</div>
</div>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock %}

myproject/templates/base/base.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
{% block header%}
    {% include '../includes/header.html' %}
{% endblock %}
</head>
  <body style="font-family: Yekan">
{% block content %}{% endblock %}
{% block footer%}
    {% include '../includes/footer.html' %}
{% endblock %}

<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

myproject/templates/includes/footer.html
{% load i18n %}
<footer class="bd-footer fixed-bottom text-white border-top">
    <nav class="navbar navbar-light bg-success p-3">
      <span style="margin-left: 40%">{% trans "Amirkabir University of Technology" %}</span>
    </nav>
</footer>

myproject/templates/includes/header.html
{% load i18n %}
{% load static %}
<header>
  <nav class="navbar navbar-expand-sm text-white bg-success mb-3 border-bottom">
  <h3 style="margin-left: 45%"> Demo</h3>
   
</div>
  </nav>
</header>